# Generated by Django 5.0.2 on 2024-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('booktitle', models.CharField(max_length=100)),
                ('bookauthor', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('authoremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
